---
- hosts: localhost
  connection: local
  gather_facts: True
  become: True

  vars:
    user_name: bill
    home_dir: "/home/{{ user_name }}"
    vim_home: "{{ home_dir }}/.vim"
    vim_bundle: "{{ vim_home }}/bundle"

  roles:
    - git
    - tools 
    - python
    - vim
